custom:
  port: 8081
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beiminzhiyu/mallConfig/
          username:
          password:
      label: master
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${custom.port}
